from __future__ import annotations
from enum import Enum, auto


class ShopItemId(Enum):
    SMOKE_BOMB = auto()
    STAMINA_POTION = auto()
    MP_POTION = auto()
    AT_POTION = auto()
    EP_POTION = auto()
    PICKAXE = auto()
    SMALL_FEATHER_BOMB = auto()
    TICKLE_TRAP = auto()
    TOLLBOOTH = auto()
    FEATHER_SWORD = auto()
    FEATHER_LONGSWORD = auto()
    BERSERK_POTION = auto()
    HASTE_POTION = auto()
    LUCK_POTION = auto()
    BRACELET_ENDURANCE = auto()
    BRACELET_GREATER_ENDURANCE = auto()
    BOW = auto()
    FEATHERARROW_QUIVER = auto()
    GREATER_FEATHER_BOMB = auto()
    POTION_VERSATILITY = auto()
    POTION_CONSTITUTION = auto()
    POTION_FOCUS = auto()
    BOOK_TICKLISH_CURSES = auto()
    FEATHER = auto()
    TICKLE_GLUE_TRAP = auto()
    PENDULUM = auto()
    MAGIC_BOOK = auto()
    SCRAP_METAL = auto()
    TRIPWIRE = auto()
    FOUR_LEAF_CLOVER = auto()
    FEATHER_SPEAR = auto()
    PINWHEEL_AXE = auto()
    AMULET_PROTECTION = auto()
    NECKLACE_FORTUNE = auto()
    STIRRUPS_STEALTH = auto()
    POTION_ENHANCER = auto()
    VIP_MINE_PASS = auto()
    LUCKY_COIN = auto()
    WYLDSAP = auto()
    RIGGED_DIE = auto()
    FEATHAGGER = auto()
    DOUBLE_FEATHAGGERS = auto()
    PIGGYBANK = auto()
    PEACOCK_POTION = auto()
    KOBOLD_PLUSHIE = auto()
    HEADBAND_RETRIBUTION = auto()
    ANKLET_RETRIBUTION = auto()
    CAMPING_EQUIPMENT = auto()
